config/routes.rb
Thynkdup::Application.routes.draw do
  resources :profiles

  resources :nutshells do
    resources :notes
  end

  resources :thynkups, only: [:create, :destroy]
  devise_for :users
  get "profiles/:id/public" => "profiles#public", as: :public
  get "pages/about"
  get "pages/how"
  get "pages/contact"
  get "pages/demo"
  get "pages/who"
  get "pages/what"
  get "pages/faq"
  get "pages/profile"

  root to: "pages#index"

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  validates_presence_of :user

  belongs_to :user,
    inverse_of: :profiles
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:public, :show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :public, :index]

  def index
    @profiles = Profile.all
  end

  def new
    @user = current_user
    @profile = Profile.new
    if current_user.nutshells.empty?
      flash[:notice] = "You must create a nutshell before working on a profile"
      redirect_to new_nutshell_path(current_user)
    end
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user
    if current_user.nutshells.empty?
      flash[:notice] = "You must create a nutshell before working on a profile"
      redirect_to new_nutshell_path(current_user)
    else
      if @profile.save
        flash[:notice] = "Welcome to your new Profile Page"
        redirect_to profile_path(@profile)
      else
        render 'new'
      end
    end
  end

  def show
    render 'public' if @profile.user != current_user
  end

  def public
  end

  def edit
    if @profile.user != current_user
      flash[:notice] = "You are not the owner of this profile"
      render 'public'
    end
  end

  def update
    if @profile.update(profile_params)
      flash[:notice] = "Your Profile has been updated"
      redirect_to profile_path(@profile)
    else
      render 'edit'
    end
  end

  def destroy
    if @profile.user == current_user
      @profile.delete
      flash[:notice] = "You just deleted your profile.  Follow the link to add profile to create a new one"
      redirect_to nutshells_path
    end
  end

  protected
  def profile_params
    params.require(:profile).permit(:occupation, :interests, :inspirations, :aspirations, :goals, :recommendations)
  end

  def set_profile
    @profile = Profile.find(params[:id])
  end

end

app/views/profiles/_form.html.erb
<%=f.input :occupation %>
<%=f.input :interests %>
<%=f.input :inspirations %>
<%=f.input :aspirations %>
<%=f.input :goals %>
<%=f.input :recommendations %>

app/views/profiles/edit.html.erb
<%=simple_form_for @profile do |f| %>
  <%= render partial: 'form', locals: { f: f }%>
  <%=f.submit "Update Profile" %>
<% end %>

app/views/profiles/index.html.erb
<% @profiles.each do |profile| %>
  <%=link_to profile.user.full_name, public_path(profile)%>
<% end %>

app/views/profiles/new.html.erb
<%=simple_form_for @profile do |f| %>
  <%= render partial: 'form', locals: { f: f }%>
  <%=f.submit "Create Profile" %>
<% end %>

app/views/profiles/public.html.erb
<%= "Welcome to #{@profile.user.full_name}'s profile" %></br>
Want to <%= link_to "thynkup", thynkups_path(friend_id: @profile.user_id), :method => :post %>?

app/views/profiles/show.html.erb
This is your profile |
<%= link_to "Update Profile", edit_profile_path(@profile) %> |
<%= link_to "Delete Profile", @profile, method: :delete, data: { confirm: 'Are you sure?' }  %>
<%= @profile.user.full_name %></br>
<%= @profile.occupation %></br>
<%= @profile.interests %></br>
<%= @profile.aspirations %></br>
<%= @profile.inspirations %></br>
<%= @profile.goals %></br>
<%= @profile.recommendations %></br>
<% @profile.user.nutshells.each do |nutshell|%>
  <%= nutshell.title + " has " + pluralize(nutshell.notes.count, "note") %>
<% end %>