config/routes.rb
Thynkdup::Application.routes.draw do
  resources :profiles

  resources :nutshells do
    resources :notes
  end

  resources :thynkups, only: [:create, :destroy]
  devise_for :users
  get "profiles/:id/public" => "profiles#public", as: :public
  get "pages/about"
  get "pages/how"
  get "pages/contact"
  get "pages/demo"
  get "pages/who"
  get "pages/what"
  get "pages/faq"
  get "pages/profile"

  root to: "pages#index"

end

app/models/nutshell.rb
class Nutshell < ActiveRecord::Base
  validates_presence_of :user
  validates_presence_of :title
  validates_presence_of :content
  serialize :keywords, Array
  validates_length_of :content, maximum: 80

  belongs_to :user,
    inverse_of: :nutshells

  has_many :categorizations,
    inverse_of: :nutshell

  accepts_nested_attributes_for :categorizations

  has_many :categories,
    through: :categorizations

  has_many :notes,
    inverse_of: :nutshell,
    dependent: :destroy

  NEEDLESS_WORDS = %w{is a an and the it my that after although though because before even if
   only now once rather since so than until when whenever where while to}

  def create_keywords
    words = (title + " " + content).downcase.split.uniq
    self.keywords = words.reject{|word| word.in?(NEEDLESS_WORDS)}
  end
end

app/controllers/nutshells_controller.rb
class NutshellsController < ApplicationController
  before_action :set_nutshell, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :wrong_thynkdup_user, only: [:show, :edit, :update, :destroy]

  def index
    @nutshells = current_user.nutshells
  end

  def edit
    @categorizations = @nutshell.categorizations.build
  end

  def new
    @nutshell = Nutshell.new
    @categorizations = @nutshell.categorizations.build
    @nutshell.user = current_user
  end

  def create
    @nutshell = Nutshell.new(nutshell_params)
    @nutshell.user = current_user
    @nutshell.create_keywords
    if @nutshell.save
      flash[:notice] = "Sounds like a great idea!"
      redirect_to nutshell_path(@nutshell)
    else
      render "new"
    end
  end

  def show
    @note = Note.new
  end

  def update
    if @nutshell.update(nutshell_params)
      flash[:notice] = "Your Thynkdup has been Updated"
      redirect_to nutshell_path(@nutshell)
    else
      render "edit"
    end
  end

  def destroy
    @nutshell.destroy
    flash[:notice] = "Your Thynkdup has been Removed.  Let's Work on Some new Ideas."
    redirect_to nutshells_path
  end

  protected

  def nutshell_params
    params.require(:nutshell).permit(:title, :content, :category_ids => [])
  end

  def wrong_thynkdup_user
   if current_user != Nutshell.find(params[:id]).user
      flash[:notice] = "This is not your Thynkdup"
      redirect_to nutshells_path
    end
  end

  def set_nutshell
    @nutshell = Nutshell.find(params[:id])
  end

end

app/views/nutshells/_form.html.erb
<%=f.input :title %>
<%=f.input :content %>
<%=f.association :categories, as: :check_boxes, label: 'Context of Thynkdup' %>

app/views/nutshells/edit.html.erb
<%= simple_form_for @nutshell do |f| %>
  <%= render partial: "form", locals: { f: f }%>
  <%=f.submit "Update Your Thynkdup"%>
<% end %>

app/views/nutshells/index.html.erb
<div>
  <% if @nutshells.count == 0 %>
    <%= link_to "Create Your First Thynkdup", new_nutshell_path %>
  <% else %>
    <% @nutshells.each do |nutshell| %>
      <div>
        <%= link_to nutshell.title, nutshell_path(nutshell) %> |
        <%= nutshell.content %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/nutshells/new.html.erb
<%= simple_form_for @nutshell do |f| %>
  <%= render partial: "form", locals: { f: f }%>
  <%=f.submit "Create Thynkdup"%>
<% end %>

app/views/nutshells/show.html.erb
<div class ="nutshell-title">
  <strong>Title: </strong> <%= @nutshell.title %> |
  <%= link_to "Update Your Thynkdup", edit_nutshell_path(@nutshell) %> |
  <%= link_to "Delete Your Thynkdup", @nutshell, method: :delete, data: { confirm: 'Are you sure?' } %> |
  <% if current_user.profiles.empty? %>
    <%= link_to "Create Your Profile", new_profile_path %>
  <% else %>
    <%= link_to "View Your Profile", profile_path(current_user.profiles.first) %>
  <% end %>
</div>
<div class ="nutshell-content"><strong>Thynkdup: </strong><%= @nutshell.content %></div>
<div>
  <% @nutshell.categories.each do |category| %>
    <% if category == @nutshell.categories[-1] %>
      <%= category.name %>
    <% else %>
      <%= category.name + " | " %>
    <% end %>
  <% end %>
</div>
<div>
  If you would like to develop your idea further
  <%= link_to "Write a New Note", new_nutshell_note_path(@nutshell, @note) %><br>
  <div>
    <% if @nutshell.notes.any? %>
      <div>My Thynkdup Notes</div>
      <% @nutshell.notes.each_with_index do |note, index| %>
        <% note_title = note.title.present? ? "Title: #{note.title}" : "#{@nutshell.title}-Note-#{(index + 1).to_s}" %>
        <strong><%= note_title %></strong> |
        <%= link_to "Edit Note", edit_nutshell_note_path(@nutshell, note) %>
        <%= link_to "Delete Note", nutshell_note_path(@nutshell, note), method: :delete, data: { confirm: 'Are you sure?' } %><br>
        <%= note.content %><br>
      <% end %>
    <% end %>
  </div>
</div>